Fire.UI/Controllers/StockTrackingController.cs
using Fire.Business.Abstrack;
using Fire.Business.Encryption;
using Fire.Entity.Concrete;
using Fire.UI.Models;
using Fire.UI.Models.AllViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using static Fire.UI.Models.AuthorizationCont;

namespace Fire.UI.Controllers
{

    public class StockTrackingController : Controller
    {
        private readonly IStockTrackingService _stockTrackingService;
        private readonly IProductTypeService _productTypeService;
        public StockTrackingController(IProductTypeService productTypeService, IStockTrackingService stockTrackingService)
        {
            _stockTrackingService = stockTrackingService;
            _productTypeService = productTypeService;
        }
        [HttpGet]
        public IActionResult List()
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var stock = _stockTrackingService.GetAll();

            ViewBag.stock = stock.Sum(x => x.totalkg);


            var query = from d1 in _productTypeService.GetAll()
                        join d2 in _stockTrackingService.GetAll() on d1.id equals d2.productid
                        where d2.branchid == Convert.ToInt32(keys.branchid)
                        select new ProductStockViewModel
                        {
                            id=d2.id,
                            name = d1.Name,
                            kg = d2.totalkg
                        };
            
            return View(new AllLayoutViewModel
            {
                TokenKeys = keys,
                stockViewModels=query.ToList()
 
            });
        }
        [HttpGet]
        public IActionResult StockUpdate(string id)
        {
            var stockid = CommondMethod.ConvertDecrypt(id);
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var stock = _stockTrackingService.GetStockByProductId(Convert.ToInt32(stockid), Convert.ToInt32(keys.branchid));
            var product = _productTypeService.GetById(Convert.ToInt32(stockid));
            return View(new AllLayoutViewModel
            {
                TokenKeys = keys,
                stockTracking = stock,
                ProductType = product,
            });
        }
        [HttpPost]
        public IActionResult StockUpdate(AllLayoutViewModel model, object s)
        {

            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var productid = HttpContext.Request.RouteValues["id"];
            var id = CommondMethod.ConvertDecrypt(productid.ToString());
            var product = _productTypeService.GetById(Convert.ToInt32(id));
            var entity = _stockTrackingService.GetStockByProductId(Convert.ToInt32(id), Convert.ToInt32(keys.branchid));
            if (entity != null)
            {
                entity.totalkg = model.stockTracking.totalkg;
                entity.ModifyDate = DateTime.Today;
                _stockTrackingService.Update(entity);
            }
            else
            {
                var valueentity = new StockTracking
                {
                    CreatedDate = DateTime.Today,
                    ModifyDate = DateTime.Today,
                    productid = Convert.ToInt32(productid),
                    totalkg = model.stockTracking.totalkg,
                    İsDelete = false,
                    branchid = Convert.ToInt32(keys.branchid)
                };
                _stockTrackingService.Create(valueentity);
            }
            return RedirectToAction("List");
        }
    }
}

Fire.UI/Views/StockTracking/List.cshtml
@using Fire.Business.Encryption
@model AllLayoutViewModel
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Stoklar <b> <input type="text" style="color:white; background-color:black;" class="form-control" value="@ViewBag.stock"  id="stock" disabled="disabled" placeholder="1,000,000.00" /> </b></h4>
                        <input type="text" class="form-control" id="txtsearch" placeholder="Stok">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <td>Ürün</td>


                                    </tr>
                                    @foreach (var customer in Model.stockViewModels)
                                    {
                                        <tr class="Search">
                                            <td>@customer.name</td>
                                            <td><input type="text" name="currency-field" style="color:white; background-color:black;" value="@customer.kg" placeholder="₺1,000,000.00" disabled="disabled"></td>
                                            <td style="text-align:right">
                                                @if (Functions.stockTrackings(customer.id).Count > 0)
                                                {
                                                    <a href="/StockTracking/StockUpdate/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn-sm btn-warning" style="margin-right:6px !important;" title="Edit">Güncelle</a>

                                                }
                                                else
                                                {
                                                    <a href="/StockTracking/StockUpdate/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn-sm btn-danger" style="margin-right:6px !important;" title="Edit">Stock Girişi</a>

                                                }
                                                @* <form action="/ProductCategoria/Delete" method="post" style="display:inline">
                                            <input type="hidden" name="id" value="@customer.id" />
                                            <button type="submit" class="btn-sm btn-danger" style="margin-right:6px !important;" data-type="confirm" title="Delete">Sil</button>
                                            </form>*@
                                            </td>
                                        </tr>
                                    }
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>



<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>

    var totalPrice2 = document.getElementsByName('currency-field');
    for (var j = 0; j < totalPrice2.length; j++) {
        totalPrice2[j].value = formatMyMoney(totalPrice2[j].value);
    }



    var totalPrice = document.getElementById('stock').value;


    document.getElementById('stock').value = formatMyMoney(totalPrice);


    function formatMyMoney(price) {

        var currency_symbol = "₺"

        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });

        return formattedOutput.format(price).replace(currency_symbol, '')
    }



    $(document).ready(function() {
        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }
        $("#txtsearch").keyup(function() {
            var searchtext = $("#txtsearch").val().toLowerCase();
            $(".Search").each(function() {
                if (!Contains($(this).text().toLowerCase(), searchtext)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            })
        })
    })


</script>

Fire.UI/Views/StockTracking/StockUpdate.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "StockUpdate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>



<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> Stok Güncelleme </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @if (ViewBag.error != null)
                        {
                            <div class="alert-danger">@ViewBag.error</div>
                        }
                        <form asp-controller="StockTracking" asp-action="StockUpdate" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputName1">Ad</label>
                                <input type="text" class="form-control whiteColor" placeholder="Banka" asp-for="ProductType.Name" id="checkNo" required />
                            </div>
                            <div class="form-group">
                                <label class="control-label" for="form-control-3">StoK Kg</label>
                                <input id="currency-field" class="form-control" asp-for="stockTracking.totalkg" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>






@*<div class="row">
    <header class="page-header">
    </header>
    <div class="col-lg-6 col-md-6">
        <form asp-controller="StockTracking" asp-action="StockUpdate" name="formadd" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label"> Ad</label>
                        <input class="form-control" type="text" asp-for="ProductType.Name" disabled="disabled" />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="form-control-3">StoK Kg</label>
                        <input id="currency-field" class="form-control" asp-for="stockTracking.totalkg" required />
                    </div>
                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" id="btn1" class=" center-block btn btn-primary">Güncelle</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>*@



<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>

<script>

    //05379597551



    //$(document).ready(function() {
    //    $('#tablodoldaltt').show();
    //    $('#tablodoldurss').show();
    //    $.ajax({
    //        type: 'GET',
    //        url: '/ProductType/GetAll',
    //        contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
    //        data: "",
    //        success: function(data) {
    //            var gelendegerler;
    //            var Adth = '<th>#</th>';
    //            var inputth = '<th>#</th>';
    //            for (var i = 0; i < data.length; i++) {
    //                Adth += '<th style="min-width:73px;">' + data[i]["name"] + '</th>';
    //                var requestData = { typeid: data[i]["id"] };
    //                $.ajax({
    //                    type: 'GET',
    //                    url: '/Customer/GetQuantityByTypeid',
    //                    contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
    //                    data: requestData,
    //                    success: function(data) {
    //                        var totalvalue = 0;
    //                        var totalprice = 0;
    //                        inputth += '<th >';
    //                        for (var j = 0; j < data.length; j++) {
    //                            totalvalue += data[j]["kg"]
    //                            totalprice += data[j]["totalprice"]
    //                            inputth += '<input style="text-align:center"  value="' + data[j]["kg"] + '"  name="' + data[j] + '_' + j + '" type="text" disabled="disabled"  form-control calcdata" >';
    //                        }
    //                        inputth += '<input style="text-align:center"  value="' + totalvalue + '"  name="' + data[j] + '_' + j + '" type="text" disabled="disabled"  form-control calcdata" >';
    //                        inputth += '</th>';
    //                        $("#tablodoldurss").html(Adth);
    //                        $("#tablodoldaltt").html(inputth);
    //                    },
    //                    error: function() {
    //                        alert('Failed to receive the Data');
    //                        console.log('Failed ');
    //                    }
    //                });
    //            }
    //        },
    //        error: function() {
    //            alert('Failed to receive the Data');
    //            console.log('Failed ');
    //        }
    //    })
    //});
</script>


<script>
    var totalPrice2 = document.getElementById('currency-field').value;
    document.getElementById('currency-field').value = formatMyMoney(totalPrice2);



    function formatMyMoney(price) {

        var currency_symbol = "₺"

        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });

        return formattedOutput.format(price).replace(currency_symbol, '')
    }



    $('#currency-field').keyup(function(event) {

        // skip for arrow keys
        if (event.which >= 37 && event.which <= 40) {
            event.preventDefault();
        }

        $(this).val(function(index, value) {
            return value
                .replace(/\D/g, "")
                .replace(/([0-9])([0-9]{2})$/, '$1.$2')
                .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",")
                ;
        });
    });
</script>