Fire.UI/Controllers/ProductTypeController.cs
using Fire.Business.Abstrack;
using Fire.Business.Encryption;
using Fire.Entity.Concrete;
using Fire.UI.Models;
using Fire.UI.Models.AllViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using static Fire.UI.Models.AuthorizationCont;

namespace Fire.UI.Controllers
{
    public class ProductTypeController : Controller
    {
        private readonly IProductTypeService _productTypeService;
        private readonly IProductQuantityService _productCategoriaService;
        private readonly IProductQuantityService _productQuantityService;
        private readonly IStockTrackingService _stockTrackingService;
        private readonly IPaymentContService _paymentContService;
        private readonly IReceiptService _receiptService;
        private readonly IProductPricesService _productPricesService;
        public ProductTypeController(IPaymentContService paymentContService, IProductPricesService productPricesService, IStockTrackingService stockTrackingService, IProductQuantityService productQuantityService
            , IProductQuantityService productCategoriaService, IProductTypeService productTypeService, IReceiptService receiptService)
        {
            _productTypeService = productTypeService;
            _productCategoriaService = productCategoriaService;
            _productQuantityService = productQuantityService;
            _stockTrackingService = stockTrackingService;
            _paymentContService = paymentContService;
            _receiptService = receiptService;
            _productPricesService = productPricesService;
        }
        [HttpGet]
        public IActionResult ProductTypeAdd()
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            return View(new AllLayoutViewModel
            {
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult ProductTypeAdd(AllLayoutViewModel model)
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var entity = new ProductType
            {
                CreatedDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                Name = model.ProductType.Name,
                İsDelete = false
            };
            var product = _productTypeService.Create(entity);
            var price = new ProductPrices
            {
                Price = "0",
                ProductId = product.id,
                IsWhat = true,
            };
            _productPricesService.Create(price);

            price = new ProductPrices
            {
                Price = "0",
                ProductId = product.id,
                IsWhat = false,
            };
            _productPricesService.Create(price);
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult List()
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            return View(new AllLayoutViewModel
            {
                productTypes = _productTypeService.GetAll(),
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult FactoryProductType(string id)
        {
            var productid = CommondMethod.ConvertDecrypt(id);
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var productcategoria = _productTypeService.GetById(Convert.ToInt32(productid));
            var entity = new ProductType
            {
                IsWhat = 2,
                //kgPrice = productcategoria.kgPrice,
                Name = productcategoria.Name,
                CreatedDate = DateTime.Now,
                ModifyDate = DateTime.Now,
                İsDelete = false,
                ProductQuantities = productcategoria.ProductQuantities,
                produckid = productcategoria.id,
            };
            _productTypeService.Create(entity);
            productcategoria.IsWhat = 3;
            _productTypeService.Update(productcategoria);
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var productid = CommondMethod.ConvertDecrypt(id);
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var productcategoria = _productTypeService.GetById(Convert.ToInt32(productid));
            return View(new AllLayoutViewModel
            {
                ProductType = productcategoria,
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult Update(AllLayoutViewModel model)
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var productid = HttpContext.Request.RouteValues["id"];
            productid = CommondMethod.ConvertDecrypt(productid.ToString());
            var product = _productTypeService.GetById(Convert.ToInt32(productid));
            product.Name = model.ProductType.Name;
            //product.kgPrice = model.ProductType.kgPrice;
            product.ModifyDate = System.DateTime.Now;
            _productTypeService.Update(product);
            return RedirectToAction("List");
        }
        [HttpGet]
        public List<ProductType> GetAll()
        {

            var ds = _productTypeService.GetAll();
            return ds;
        }
        [HttpPost]
        public List<string> deneme()
        {
            var products = _productTypeService.GetAll();
            var query = from d1 in products.Where(x => x.İsDelete == false)
                        join d2 in _productPricesService.GetAll() on d1.id equals d2.ProductId into gj
                        from subget in gj.DefaultIfEmpty()
                        where subget.İsDelete == false && subget.IsWhat == true
                        select new
                        {
                            Name = d1.Name,
                            Price = subget.Price == null ? "0" : subget.Price.ToString(),
                        };
            //obje türünde session doldurmak
            HttpContext.Session.SetString("sessionProductType", JsonConvert.SerializeObject(products));
            JsonConvert.SerializeObject(products);
            List<string> dd = new List<string>();
            foreach (var item in query.ToList())
            {
                dd.Add(item.Name + "," + item.Price);
            }
            return dd;
        }
        [HttpPost]
        public IActionResult ekle(AllLayoutViewModel model)
        {

            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var customerid = HttpContext.Session.GetString("customerid");
            HttpContext.Session.SetString("customerid", "");
            int id = Convert.ToInt32(customerid);



            if (model.Factory.CreatedDate.Year == 0001)
                model.Factory.CreatedDate = DateTime.Now;
            var quantitylist = _receiptService.GetReceiptByCustomerId(id, Convert.ToInt32(keys.branchid), true);
            var valuedate = quantitylist.Where(x => x.ReceiptDate == model.Factory.CreatedDate).FirstOrDefault();
            int quantity = 0;
            decimal totalkg = 0;
            decimal totalprice = 0;
            var data = new Receipt();
            if (valuedate != null)
            {
                var entity = new Receipt
                {
                    BranchId = Convert.ToInt32(keys.branchid),
                    DailyTakeCount = valuedate.DailyTakeCount + 1,
                    CustomerId = id,
                    ReceiptDate = model.Factory.CreatedDate,
                    İsDelete = false,
                    CreatedDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    IsWhat = true,
                };
                data = _receiptService.Create(entity);
            }
            else
            {
                var entity = new Receipt
                {
                    BranchId = Convert.ToInt32(keys.branchid),
                    DailyTakeCount = 1,
                    CustomerId = id,
                    ReceiptDate = model.Factory.CreatedDate,
                    İsDelete = false,
                    CreatedDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    IsWhat = true,
                };
                data = _receiptService.Create(entity);
            }


            var gelenform = HttpContext.Request.Form.ToList().Where(x => x.Value != "0" && x.Key != "__RequestVerificationToken" && x.Key != "Factory.CreatedDate" && x.Value.Count > 1).ToList();
            for (int i = 0; i < gelenform.Count; i++)
            {
                string key = gelenform[i].Key.ToString();
                var value = gelenform[i].Value.ToList();

Fire.UI/Views/ProductType/Add.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "Add";
    Layout = "~/Views/Shared/_Layout.cshtml";
}





<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fiş Ekleme</h4>



                        <form asp-controller="ProductType" asp-action="ekle" class="forms-sample">
                            <span>Fiş Tarihi:</span><input type="date" asp-for="Factory.CreatedDate" />
                            <button type="submit" class="btn btn-primary btn-rounded btn-fw btn-sm"> Kaydet</button>
                            <div class="table-responsive">
                                <table id="dtBasicExample3" class="">
                                    <thead>
                                        <tr class="Search" id="tablodoldurss">
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="Search" id="tablodoldaltt"></tr>
                                    </tbody>
                                </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>


@*<div class="row">
    <header class="page-header">
    </header>
    <div class="col-lg-6 col-md-6">
        <form asp-controller="ProductType" asp-action="ekle">
            <span>Fiş Tarihi:</span><input type="date" asp-for="Factory.CreatedDate" />
            <table id="dtBasicExample3" class="table table-striped table-bordered"
                   cellspacing="0" style="text-align:center">
                <thead>
                    <tr class="odd" id="tablodoldurss"></tr>

                </thead>
                <tbody>
                    <tr class="odd" id="tablodoldaltt"></tr>
                </tbody>
            </table>
        </form>
    </div>
</div>
*@






<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script>
    function geneltoplam(toplam) {
        var ilkdeger = $("#geneltoplam").val();
        var toplanan = parseFloat(ilkdeger) + parseFloat(toplam);
        $("#geneltoplam").val(toplanan);
    };
    function focusOn(this) {
    }

    function isNumberKey(evt) {
        console.log(evt);
        var charCode = (evt.which) ? evt.which : event.keyCode;
        if (charCode > 31 && (charCode < 48 || charCode > 57))
            return false;
        return true;
    }



    function keyCapt(e) {

        console.log(e);
        if (e.value != '' && e.value > 0) {

            var name = $(e).attr('name');
            var spt = name.split(","); //siplit 0 renk adı / siplir 1 fiyat
            var ilk = spt[0];

            var carpim = 1;

            //ilk input adet değerini al
            var ilkdeger = $("#" + ilk + "totalQuantity").val();
            ilkdeger = parseFloat(ilkdeger) + parseFloat(e.value);
            console.log(ilkdeger);

            //girilen adetleri sürekli toplayarak toplam adet inputuna at
            $("#" + ilk + "totalQuantity").val(ilkdeger);

            //girilen adet ile fiyatın çarpımı
            carpim = parseFloat(ilkdeger) * parseFloat(spt[1]);

            //arka tarafdaki toplam fiyat
            $("#" + ilk + "totalPrice").val(carpim);

            //ekranda gözükecek toplam fiyat
            $("#" + ilk + "GozukecekPrice").val(carpim);



            geneltoplam(carpim);
        }
    };
</script>
<script>
    $(document).ready(function() {
        $('#tablodoldaltt').show();
        $('#tablodoldurss').show();
        $.ajax({
            type: 'POST',
            url: '/ProductType/deneme',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: "",
            success: function(data) {
                var Adth = '<th>#</th>';
                var inputth = '<th>#</th>';
                var sda;
                var value = "";
                var d = "";

                for (var i = 0; i < data.length; i++) {
                    Adth += '<th style="min-width:73px;">' + data[i] + '</th>';
                    value = data[i].split(',');
                    console.log(value[1]);
                    inputth += '<th >';
                    for (var j = 0; j < 50; j++) {

                        if (j == 0) {

                            inputth += '<span>toplam :</span><input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="0" name="' + data[i] + '_' + i + ' tpl" type="text" min="0" form-control calcdata" >';

                            inputth += '<span>fiyat :</span><input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="0" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';

                            inputth += '<input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="" disabled="disabled" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';
                        }
                        inputth += '<input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="0" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';
                    }
                    inputth += '</th>';
                }
                //inputth += '<th><button type="submit" style="background-color:#96885a; color:white; " class="btn width-md waves-effect waves-light form-control"> Add +</button>    <span>Genel Toplam</span><input style="text-align:center" value="0" name="geneltoplam"  id="geneltoplam" type="text" disabled="disabled"  form-control calcdata" ></th>';
                $("#tablodoldurss").html(Adth);
                $("#tablodoldaltt").html(inputth);
            },
            error: function() {
                alert('Failed to receive the Data');
                console.log('Failed ');
            }
        })
    });
</script>

Fire.UI/Views/ProductType/AddProductWithCustomerid.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "AddProductWithCustomerid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <header class="page-header">
    </header>
    <form asp-action="AddProductWithCustomerid" asp-controller="ProductType" method="post">
        <table class="table table-bordered">
            <tr>
       @*         <td>@Model.ProductType.Name @Model.ProductType.kgPrice</td>*@
            </tr>

            @for (var i = 0; i < 50; i++)
            {
                <tr>
                    <td><input type="text" name="values[value]"></td>

                </tr>
            }

        </table>
        <div class="form-group row">
            <div class="col-md-10 offset-md-2">
                <button type="submit" id="btn1" class=" center-block btn btn-primary">Ekle</button>
            </div>
        </div>

    </form>
</div>

Fire.UI/Views/ProductType/List.cshtml
@using Fire.Business.Encryption
@model AllLayoutViewModel
@{
    ViewData["Title"] = "List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Ürünler</h4>
                        <input type="text" class="form-control" id="txtsearch" placeholder="Ürünler">
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <td class="whiteColor">Ürün</td>
                                        <td class="whiteColor"> Alış Fiyat</td>
                                        <td class="whiteColor"> Satış Fiyat</td>

                                    </tr>
                                    @foreach (var customer in Model.productTypes)
                                    {
                                        <tr class="Search">
                                            <td class="whiteColor">@customer.Name</td>
                                            <td class="whiteColor">@Functions.PriceToProduct(customer.id,true)</td>
                                            <td class="whiteColor">@Functions.PriceToProduct(customer.id,false)</td>

                                            <td style="text-align:right">
                                                <a href="/ProductType/Update/@CommondMethod.ConvertToEncrypt(@customer.id.ToString())" name="id" class="btn btn-warning" style="margin-right:6px !important;" title="Edit">Güncelle</a>
                                                <a href="/Customer/SetPriceByProductId/@customer.id" name="id" class="btn btn-success" style="margin-right:6px !important;" title="Edit">Alış</a>
                                                <a href="/Factory/SetPriceByProductId/@customer.id" name="id" class="btn btn-success" style="margin-right:6px !important;" title="Edit">Satış</a>

                                                @*  <form action="/ProductType/Delete" method="post" style="display:inline">
                                            <input type="hidden" name="id" value="@customer.id" />
                                            <button type="submit" class="btn-sm btn-danger" style="margin-right:6px !important;" data-type="confirm" title="Delete">Sil</button>
                                            </form>*@
                                            </td>
                                        </tr>
                                    }
                                </thead>
                                <tbody>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>




  

    $(document).ready(function() {
        function Contains(text_one, text_two) {
            if (text_one.indexOf(text_two) != -1)
                return true;
        }
        $("#txtsearch").keyup(function() {
            var searchtext = $("#txtsearch").val().toLowerCase();
            $(".Search").each(function() {
                if (!Contains($(this).text().toLowerCase(), searchtext)) {
                    $(this).hide();
                }
                else {
                    $(this).show();
                }
            })
        })
    })


 

</script>

Fire.UI/Views/ProductType/ProductTypeAdd.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "ProductTypeAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>



<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> Ürün Kaydet </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @if (ViewBag.error != null)
                        {
                            <div class="alert-danger">@ViewBag.error</div>
                        }
                        <form asp-controller="ProductType" asp-action="ProductTypeAdd" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputName1" class="whiteColor">Ürün</label>
                                <input type="text" class="form-control whiteColor" placeholder="Ürün" asp-for="ProductType.Name" id="checkNo" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>





  
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>


<script>




    $('#giveMany').keyup(function(event) {

        // skip for arrow keys
        if (event.which >= 37 && event.which <= 40) {
            event.preventDefault();
        }

        $(this).val(function(index, value) {
            return value
                .replace(/\D/g, "")
                .replace(/([0-9])([0-9]{2})$/, '$1.$2')
                .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",")
                ;
        });
    });



</script>
 

Fire.UI/Views/ProductType/Update.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>



<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> Ürün Güncelleme </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @if (ViewBag.error != null)
                        {
                            <div class="alert-danger">@ViewBag.error</div>
                        }
                        <form asp-controller="ProductType" asp-action="Update" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputName1">Ürün</label>
                                <input type="text" class="form-control whiteColor" placeholder="Ürün" asp-for="ProductType.Name" id="checkNo" required />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputName1">Fiyat</label>
                                <input type="text" class="form-control whiteColor" placeholder="Ürün" asp-for="ProductType.kgPrice" id="giveMany" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>

    var price = document.getElementById('giveMany').value;

    document.getElementById('giveMany').value = formatMyMoney(price);



    function formatMyMoney(price) {

        var currency_symbol = "₺"

        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });

        return formattedOutput.format(price).replace(currency_symbol, '')
    }

    //function myfocus(x) {
    //    x.style.background = "yellow";
    //}

    $('#giveMany').keyup(function(event) {

        // skip for arrow keys
        if (event.which >= 37 && event.which <= 40) {
            event.preventDefault();
        }

        $(this).val(function(index, value) {
            return value
                .replace(/\D/g, "")
                .replace(/([0-9])([0-9]{2})$/, '$1.$2')
                .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",")
                ;
        });
    });



</script>