Fire.UI/Controllers/FactoryController.cs
using Fire.Business.Abstrack;
using Fire.Business.Encryption;
using Fire.Entity.Concrete;
using Fire.UI.Models;
using Fire.UI.Models.AllViewModels;
using Fire.UI.Models.FactoryStockControll;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using static Fire.UI.Models.AuthorizationCont;

namespace Fire.UI.Controllers
{
    public class FactoryController : Controller
    {
        private readonly IFactoryService _factoryservice;
        private readonly IFactoryQuantityService _factoryQuantityService;
        private readonly IProductTypeService _productTypeService;
        private readonly IStockTrackingService _stockTrackingService;
        private readonly IPaymentContService _paymentContService;
        private readonly IReceiptService _receiptService;
        private readonly IProductPricesService _productPricesService;
        public FactoryController(IProductPricesService productPricesService, IPaymentContService paymentContService, IStockTrackingService stockTrackingService, IFactoryQuantityService factoryQuantityService,
            IProductTypeService productTypeService, IFactoryService factoryservice, IReceiptService receiptService)
        {
            _productPricesService = productPricesService;
            _factoryservice = factoryservice;
            _factoryQuantityService = factoryQuantityService;
            _productTypeService = productTypeService;
            _stockTrackingService = stockTrackingService;
            _paymentContService = paymentContService;
            _receiptService = receiptService;
        }
        #region
        public IActionResult List()
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            ViewBag.results = _factoryservice.GetAll();
            return View(new AllLayoutViewModel
            {
                Factories = _factoryservice.GetAll(),
                TokenKeys = keys,
            });
        }
        public IActionResult AddFactory()
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            return View(new AllLayoutViewModel
            {
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult AddFactory(AllLayoutViewModel model)
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var factory = new Factory
            {
                CreatedDate = System.DateTime.Now,
                ModifyDate = System.DateTime.Now,
                İsDelete = false,
                name = model.Factory.name,
                Phone = model.Factory.Phone,
                companyId = Convert.ToInt32(keys.companyId)
            };
            _factoryservice.Create(factory);
            return RedirectToAction("List");
        }
        [HttpGet]
        public IActionResult Update(string id)
        {
            var factoryid = CommondMethod.ConvertDecrypt(id);
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var value = _factoryservice.GetById(Convert.ToInt32(factoryid));
            HttpContext.Session.SetString("FactoryId", id);
            return View(new AllLayoutViewModel
            {
                Factory = value,
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult Update(AllLayoutViewModel model)
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var factoryid = HttpContext.Session.GetString("FactoryId");
            var deger = _factoryservice.GetById(Convert.ToInt32(CommondMethod.ConvertDecrypt(factoryid.ToString())));
            deger.name = model.Factory.name;
            deger.Phone = model.Factory.Phone;
            deger.ModifyDate = System.DateTime.Now;
            _factoryservice.Update(deger);
            return RedirectToAction("List");
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var customer = _factoryservice.GetById(id);
            customer.İsDelete = true;
            _factoryservice.Update(customer);
            return RedirectToAction("List");
        }
        #endregion
        [HttpGet]
        public IActionResult FactoryReceptAddByFactoryid(string id)
        {
            var ids = CommondMethod.ConvertDecrypt(id);
            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            HttpContext.Session.SetString("factoryId", ids);
            var message = HttpContext.Session.GetString("factoryError");
            if (!string.IsNullOrEmpty(message) && message != "00")
            {
                ViewBag.message = message;
                HttpContext.Session.SetString("factoryError", "00");
            }
            HttpContext.Session.SetString("updatefactory", "99");

            return View(new AllLayoutViewModel
            {
                productTypes = _productTypeService.GetAll(),
                TokenKeys = keys,
            });
        }
        [HttpPost]
        public IActionResult FactoryReceptAddByFactoryid(AllLayoutViewModel allLayoutViewModel)
        {

            var Authorization = HttpContext.Session.GetString("token");
            TokenKeys keys = AuthorizationCont.Authorization(Authorization);
            if (keys == null)
                return Redirect("/Error/401");
            var factoryid = HttpContext.Session.GetString("factoryId");
            int id = Convert.ToInt32(factoryid);

            if (allLayoutViewModel.Factory.CreatedDate.Year == 0001)
                allLayoutViewModel.Factory.CreatedDate = DateTime.Now;
            var quantitylist = _receiptService.GetReceiptByCustomerId(id, Convert.ToInt32(keys.branchid), false);

            var valuedate = quantitylist.Where(x => x.ReceiptDate.Year == allLayoutViewModel.Factory.CreatedDate.Year && x.ReceiptDate.Month == allLayoutViewModel.Factory.CreatedDate.Month && x.ReceiptDate.Day == allLayoutViewModel.Factory.CreatedDate.Day).FirstOrDefault();
            int quantity = 0;
            decimal totalkg = 0;
            decimal totalprice = 0;
            var data = new Receipt();
            var receiptEntity = new Receipt();
            if (valuedate != null)
            {
                receiptEntity = new Receipt
                {
                    BranchId = Convert.ToInt32(keys.branchid),
                    DailyTakeCount = valuedate.DailyTakeCount + 1,
                    CustomerId = id,
                    ReceiptDate = allLayoutViewModel.Factory.CreatedDate,
                    İsDelete = false,
                    CreatedDate = DateTime.Now,
                    ModifyDate = DateTime.Now,
                    IsWhat = false,
                };

            }
            else
            {
                receiptEntity = new Receipt
                {
                    BranchId = Convert.ToInt32(keys.branchid),
                    DailyTakeCount = 1,
                    CustomerId = id,
                    ReceiptDate = allLayoutViewModel.Factory.CreatedDate,
                    İsDelete = false,
                    CreatedDate = DateTime.Now,
                    ModifyDate = DateTime.Now
                };

            }
            data = _receiptService.Create(receiptEntity);
            var gelenform = HttpContext.Request.Form.ToList().Where(x => x.Value != "0" && x.Value.Count > 1 && x.Key != "__RequestVerificationToken" && x.Key != "Factory.CreatedDate").ToList();
            //var factorystockvalue = FactoryStockControllViewModel.stockcontroll(gelenform, _stockTrackingService, _productTypeService, Convert.ToInt32(keys.branchid));
            for (int i = 0; i < gelenform.Count; i++)
            {
                string key = gelenform[i].Key.ToString();

                var value = gelenform[i].Value.ToList();
                string[] arra = key.Split(',');
                var keyname = arra[0];
                var keyvalue = arra[1];
                var s = keyvalue.ToString().IndexOf("_");
                keyvalue = keyvalue.Remove(s);
                var productypeid = _productTypeService.GetProductTypeByName(keyname);
                var productPrice = _productPricesService.GetPriceByProductId(productypeid.id, false);
                decimal val = 0;
                decimal tpl = 0;
                int tok = 0;

                if (value.Count > 0)
                {
                    var stockcontroll = new StockTracking();

                    if (Convert.ToDecimal(value[1]) > 0)
                    {
                        stockcontroll = _stockTrackingService.GetStockByProductId(productypeid.id, Convert.ToInt32(keys.branchid));
                        if (stockcontroll is null)
                        {

Fire.UI/Views/Factory/AddFactory.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "AddFactory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 

<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>




<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fabrika Ekleme</h4>
                        <form asp-controller="Factory" asp-action="AddFactory" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Fabrika isim</label>
                                <input type="text" class="form-control whiteColor" placeholder="İsim" asp-for="Factory.name" required />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Telefon</label>
                                <input type="text" class="form-control whiteColor" placeholder="Telefon" id="unitPrice" asp-for="Factory.Phone" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>

Fire.UI/Views/Factory/FactoryReceptAddByFactoryid.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "FactoryReceptAddByFactoryid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">

            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>
        <div class="row">
            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fiş Ekleme</h4>
                        @if (ViewBag.message != null)
                        {
                            <div class="alert-danger">@ViewBag.message</div>
                        }

                        <form asp-controller="Factory" asp-action="FactoryReceptAddByFactoryid" class="forms-sample">
                            <span>Fiş Tarihi:</span><input type="date" asp-for="Factory.CreatedDate" />
                            <button type="submit" class="btn btn-primary btn-rounded btn-fw btn-sm"> Kaydet</button>
                            <div class="table-responsive">
                                <table id="dtBasicExample3" class="">
                                    <thead>
                                        <tr class="Search" id="tablodoldurss">
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr class="Search" id="tablodoldaltt"></tr>
                                    </tbody>
                                </table>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>









@*<div class="row">
    <header class="page-header">
        @if (ViewBag.message != null)
        {
            <div class="alert-danger">@ViewBag.message</div>
        }

    </header>
    <div class="col-lg-6 col-md-6">

        <form asp-controller="Factory" asp-action="FactoryReceptAddByFactoryid">
            <span>Fiş Tarihi:</span><input type="date" asp-for="Factory.CreatedDate" />
            <table id="dtBasicExample3" class="table table-striped table-bordered"
                   cellspacing="0" style="text-align:center">
                <thead>
                    <tr class="odd" id="tablodoldurss"></tr>

                </thead>
                <tbody>
                    <tr class="odd" id="tablodoldaltt"></tr>
                </tbody>
            </table>
        </form>
    </div>
</div>*@


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>


<script>
    $(document).ready(function() {
        $('#tablodoldaltt').show();
        $('#tablodoldurss').show();
        $.ajax({
            type: 'POST',
            url: '/Factory/ProductList',
            contentType: 'application/x-www-form-urlencoded; charset=UTF-8',
            data: "",
            success: function(data) {
                var Adth = '<th>#</th>';
                var inputth = '<th>#</th>';
                var value = "";
                var d = "";
                console.log(data);
                for (var i = 0; i < data.length; i++) {
                    Adth += '<th style="min-width:73px;">' + data[i] + '</th>';
                    value = data[i].split(',');
                    inputth += '<th >';
                    for (var j = 0; j < 50; j++) {

                        if (j == 0) {
                            inputth += '<span>fiyat :</span><input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="0" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';

                            inputth += '<input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="" disabled="disabled" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';
                        }

                        inputth += '<input style="text-align:center" onkeyup="keyCapt(this)" onkeypress="isNumberKey(this)" value="0" name="' + data[i] + '_' + i + '" type="text" min="0" form-control calcdata" >';

                    }
                    inputth += '</th>';
                }
                //inputth += '<th><button type="submit" style="background-color:#96885a; color:white; " class="btn width-md waves-effect waves-light form-control"> Add +</button>    <span>Genel Toplam</span><input style="text-align:center" value="0" name="geneltoplam"  id="geneltoplam" type="text" disabled="disabled"  form-control calcdata" >  </th>';
                $("#tablodoldurss").html(Adth);
                $("#tablodoldaltt").html(inputth);
            },
            error: function() {
                alert('Failed to receive the Data');
                console.log('Failed ');
            }
        })
    });
</script>

Fire.UI/Views/Factory/FullPaid.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "FullPaid";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<head>
    <style>
        #currency-field {
            color: black;
        }

        #amaoundPaid {
            color: black;
        }

        #odenecek {
            color: black;
        }

        #giveMany {
            color: white;
        }
    </style>
</head>

<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
            @if (ViewBag.error != null)
            {
                <div class="alert-danger">@ViewBag.error</div>
            }
            else if (@ViewBag.success != null)
            {
                <div class="alert-success">@ViewBag.success</div>
            }
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Ödeme</h4>
                        <form asp-controller="Factory" asp-action="FullPaid" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputName1">Toplam  Ödenecek Tutar</label>
                                <input type="text" class="form-control" value="@Model.PaymentViewModel.totalPrice" name="currency-field" id="currency-field" disabled="disabled" placeholder="₺1,000,000.00" />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail3">Ödenmiş Tutar</label>
                                <input type="text" class="form-control" value="@Model.PaymentViewModel.amountPaid" disabled="disabled" name="currency-field" id="amaoundPaid" />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputEmail3"> Ödenecek Tutar</label>
                                <input type="text" class="form-control" value="@Model.PaymentViewModel.unPaid" id="odenecek" disabled="disabled" name="currency-field" />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword4">Verilen Miktar</label>
                                <input type="text" id="giveMany" class="form-control" placeholder="" onkeyup="formatMyMoney(this)" name="deger" required />
                            </div>



                            <button type="submit" id="btn1" class="btn btn-primary mr-2">Ödeme Al</button>

                        </form>
                    </div>
                </div>
            </div>
        </div>


    </div>

</div>

@*
<div class="row">
    <header class="page-header">
        @if (ViewBag.error != null)
        {
            <div class="alert-danger">@ViewBag.error</div>
        }
        else if (@ViewBag.success != null)
        {
            <div class="alert-success">@ViewBag.success</div>
        }
    </header>
    <div class="col-lg-6 col-md-6">
        <form asp-controller="Factory" asp-action="FullPaid" name="formadd" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">

                    <span>Toplam  Ödenecek Tutar</span> <input type="text" value="@Model.PaymentViewModel.totalPrice" name="currency-field" id="currency-field" disabled="disabled" placeholder="₺1,000,000.00" />

                    <br />
                    <span>Ödenmiş Tutar</span> <input type="text" value="@Model.PaymentViewModel.amountPaid" disabled="disabled" name="currency-field" id="amaoundPaid" />
                    <br />
                    <span>Ödenecek Tutar </span> <input type="text" value="@Model.PaymentViewModel.unPaid" id="odenecek" disabled="disabled" name="currency-field" />
                    <br />
                    <div class="form-group">
                        <label class="control-label"> Verilen Miktar</label>
                        <input id="giveMany" class="form-control" type="text" onkeyup="formatMyMoney(this)" name="deger" required /><span>₺</span>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" id="btn1" class=" center-block btn btn-primary">Öde</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
       
    </div>
</div>
*@


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>


<script>

    //function myfocus(x) {
    //    x.style.background = "yellow";
    //}
    var totalPrice2 = document.getElementById('currency-field').value;
    var totalPrice3 = document.getElementById('amaoundPaid').value;
    var totalPrice4 = document.getElementById('odenecek').value;

    document.getElementById('currency-field').value = formatMyMoney(totalPrice2) + " " + "₺";
    document.getElementById('amaoundPaid').value = formatMyMoney(totalPrice3) + " " + "₺";
    document.getElementById('odenecek').value = formatMyMoney(totalPrice4) + " " + "₺";

    function formatMyMoney(price) {

        var currency_symbol = "₺"

        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });

        return formattedOutput.format(price).replace(currency_symbol, '')
    }


    $(document).ready(function() {
        var result;
        result = document.getElementById("odenecek").value;
        if (result == 0) {
            $('#btn1').prop('disabled', true);
        }

    });
    $('#giveMany').keyup(function(event) {

        // skip for arrow keys
        if (event.which >= 37 && event.which <= 40) {
            event.preventDefault();
        }

        $(this).val(function(index, value) {
            return value
                .replace(/\D/g, "")
                .replace(/([0-9])([0-9]{2})$/, '$1.$2')
                .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",")
                ;
        });
    });



</script>
<script type="text/javascript">


</script>

Fire.UI/Views/Factory/SetPriceByProductId.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "SetPriceByProductId";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<head>
    <style>
        .whiteColor {
            color: white !important;
        }
    </style>
</head>



<div class="main-panel">
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title"> Ürün Fiyat </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                </ol>
            </nav>
        </div>

        <div class="row">
            <div class="col-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        @if (ViewBag.error != null)
                        {
                            <div class="alert-danger">@ViewBag.error</div>
                        }
                        <form asp-controller="Factory" asp-action="SetPriceByProductId" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputName1">Ürün</label>
                                <input type="text" class="form-control whiteColor" style="background-color:black;" placeholder="Ürün" asp-for="productPriceByProduct.Name" id="checkNo" required disabled="disabled" />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputName1">Fiyat</label>
                                <input type="text" class="form-control whiteColor" placeholder="Fiyat" id="giveMany" asp-for="productPriceByProduct.Price" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Kaydet</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/ace/1.4.12/snippets/javascript.min.js"></script>
<script src="/lib/jquery/dist/jquery.min.js"></script>
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

<script>

    var SumResult = document.getElementById("giveMany");
    SumResult.innerHTML = formatMyMoney(SumResult.innerHTML);

    function formatMyMoney(price) {

        var currency_symbol = "₺"

        var formattedOutput = new Intl.NumberFormat('tr-TR', {
            style: 'currency',
            currency: 'TRY',
            minimumFractionDigits: 2,
        });

        return formattedOutput.format(price).replace(currency_symbol, '')
    }


    $('#giveMany').keyup(function(event) {

        // skip for arrow keys
        if (event.which >= 37 && event.which <= 40) {
            event.preventDefault();
        }

        $(this).val(function(index, value) {
            return value
                .replace(/\D/g, "")
                .replace(/([0-9])([0-9]{2})$/, '$1.$2')
                .replace(/\B(?=(\d{3})+(?!\d)\.?)/g, ",")
                ;
        });
    });



</script>

Fire.UI/Views/Factory/Update.cshtml
@model AllLayoutViewModel
@{
    ViewData["Title"] = "Update";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@*<div class="row">
    <header class="page-header">
    </header>
    <div class="col-lg-6 col-md-6">
        <form asp-controller="Factory" asp-action="Update" name="formadd" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="control-label"> Fabrika isim</label>
                        <input id="productName" class="form-control" type="text" asp-for="Factory.name" required />
                    </div>
                    <div class="form-group">
                        <label class="control-label" for="form-control-3">Telefon</label>
                        <input id="unitPrice" class="form-control" asp-for="Factory.Phone" required />
                    </div>
                    <div class="form-group row">
                        <div class="col-md-10 offset-md-2">
                            <button type="submit" id="btn1" class=" center-block btn btn-primary">Güncelle</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>

</div>*@



<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">
            <div class="col-md-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Fabrika Güncelleme</h4>
                        <form asp-controller="Factory" asp-action="Update" name="formadd" method="post" enctype="multipart/form-data">
                            <div class="form-group">
                                <label for="exampleInputUsername1">Fabrika isim</label>
                                <input type="text" class="form-control" placeholder="İsim" asp-for="Factory.name" required />
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Telefon</label>
                                <input type="text" class="form-control" placeholder="Telefon" id="unitPrice" asp-for="Factory.Phone" required />
                            </div>
                            <button type="submit" class="btn btn-primary mr-2">Güncelle</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <footer class="footer">
        <div class="d-sm-flex justify-content-center justify-content-sm-between">
            <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Tüm Haklar Saklıdır. © 2023</span>
            <!-- <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">  <a href="https://www.bootstrapdash.com/bootstrap-admin-template/" target="_blank">Bootstrap admin templates</a> from Bootstrapdash.com</span> -->
        </div>
    </footer>
</div>